export const SPELLS_DATABASE = [
  {
    name: "Arcane Shield",
    level: "1",
    actionSpeed: "Fast Action",
    spellType: "Arcane",
    range: "Self",
    area: "Self",
    duration: "end of next round",
    description: "Get +10 deflection and +1 DR for the duration. You are immune to one Magic Missile for the duration. Successfully casting a cantrip, casting a spell, or performing any kind of strike ends this spell.\n\nYou may pay additional Spell Points to cast the spell, raising the number of Magic Missiles you are immune to by one for each additional point you pay.",
    cost: "1+"
  },
  {
    name: "Burning Hands",
    level: "1",
    actionSpeed: "Fast Action",
    spellType: "Arcane",
    range: "2 units burst",
    area: "2 units burst",
    duration: "Instantaneous",
    description: "You unleash a wide flame from your hands. Roll Magic against Deflection for each creature in the area. Those you succeed against receive 2 fire damage. The rest receive 1 fire damage.",
    cost: "1+"
  },
  {
    name: "Bestow Curse",
    level: "1",
    actionSpeed: "Slow Action (Interruptible)",
    spellType: "Occult",
    range: "10 Units",
    area: "Single Target",
    duration: "Varies",
    description: "Occult Magic check against target's Will. On success, choose two of the following:\n• They become disoriented (-5 penalty on all rolls) until the end of the next 2 rounds.\n• They become slowed (+1 drag to all actions, -1 Movement) until the end of the next 2 rounds.\n• They become vulnerable (-5 to all defenses) until the end of the next 2 rounds.\n• They become discouraged (they deal -1 damage) until the end of combat.\n\nIf you roll a natural 20, the target also receives 1 damage (ignores all DR). You may spend additional spell points as you cast the spell. Choose one additional mode for each additional spell point spent.",
    cost: "1+"
  },
  {
    name: "Cure",
    level: "1",
    actionSpeed: "Fast Action",
    spellType: "Divine / Nature / Bardic",
    range: "10 Units",
    area: "Single Target",
    duration: "Instantaneous",
    description: "Choose a target within range. Heal them for 1 HP, or 2 if the spell was cast using Divine magic. If the target is dying, it becomes stabilized.\n\nYou may spend additional spell points as you cast this spell. For each additional spell point you heal them for 1 more HP. You may choose to cast the spell as a slow, interruptible action. If you do, heal up to two targets instead.",
    cost: "1+"
  },
  {
    name: "Dissonant Whispers",
    level: "1",
    actionSpeed: "Slow Action (Interruptible)",
    spellType: "Occult / Bardic",
    range: "12 Units",
    area: "Single Target",
    duration: "Instantaneous",
    description: "Magic check against Will. You channel psychic disturbance into the mind of an you can see within range. On success, the target becomes disoriented (-5 penalty on all rolls) and receives:\n• Normal Success: 1 Psychic Damage, ignoring all DR.\n• Major Success: 2 Psychic Damage, ignoring all DR.\n• Critical Success: 3 Psychic Damage, ignoring all DR.\nOn success, if you rolled 20 on the die, the target is also frightened (they must use the dodge or dash action, and stride as far away as possible from the source).",
    cost: "1+"
  },
  {
    name: "Divine Guidance",
    level: "Cantrip",
    actionSpeed: "Average Action",
    spellType: "Divine",
    range: "Touch",
    area: "Single Target",
    duration: "Until dismissed/unconscious",
    description: "Choose a target within range. They gain advantage on checks of: Religion, Speech skills in conversations with religious context, Insight, Medicine, Perception checks against demons and undead. The spell ends when you are unconscious, when you cast this spell again, or when you dismiss it.",
    cost: "0"
  },
  {
    name: "Divine Interference",
    level: "1",
    actionSpeed: "Fast Action",
    spellType: "Divine",
    range: "15 units",
    area: "Single Target",
    duration: "end of current round",
    description: "Choose a target within range. They get +5 Deflection against the first attack for the duration.",
    cost: "1"
  },
  {
    name: "Eldritch Shield",
    level: "1",
    actionSpeed: "Fast Action",
    spellType: "Occult",
    range: "Self",
    area: "Self",
    duration: "end of next round",
    description: "Get +10 Deflection. If you are hit by an attack against your Deflection, the enemy that dealt the damage loses 1 HP. Successfully casting another spell or cantrip ends this spell.",
    cost: "1"
  },
  {
    name: "Elemental Flare",
    level: "Cantrip",
    actionSpeed: "Average Action",
    spellType: "Arcane",
    range: "12 Units",
    area: "Single Target",
    duration: "Instantaneous",
    description: "Arcane Magic check against Deflection. Shoot an elemental flare at a target in range. Choose its damage type: lightning, fire or ice. On success:\n• Normal Success: deal 2 Damage.\n• Major Success: deal 3 Damage.\n• Critical Success: deal 4 Damage.\n\nOn success, if you rolled 20, depending on the damage type, the target also:\n• Fire: they start burning until the end of the next round (1 fire damage/round).\n• Lightning: they become vulnerable (-5 to all defenses) for 1 round.\n• Ice: they become slowed (+1 drag to all actions, -1 movement) for 1 round.",
    cost: "0"
  },
  {
    name: "Elemental Pulse",
    level: "1",
    actionSpeed: "Slow Action (Interruptible)",
    spellType: "Arcane",
    range: "10 Units",
    area: "2-unit radius",
    duration: "Instantaneous",
    description: "Choose an ally within range or yourself. Choose fire, ice, or lightning. A pulse of the chosen elemental energy bursts from the chosen target, with a 2-unit radius. Roll Magic against each Deflection for each creature within the radius. Those you succeed against receive 2 damage of the chosen type. The rest receive 1 damage of the chosen type.",
    cost: "1+"
  },
  {
    name: "Entangle",
    level: "1",
    actionSpeed: "Slow Action (Interruptible)",
    spellType: "Nature",
    range: "15 units",
    area: "Targeted area",
    duration: "10 minutes",
    description: "Vines erupt from the ground. Roll Nature Magic against Deflection for each enemy in the area. Each enemy that you've succeeded against becomes restrained. The affected area is difficult terrain. At the start of each round, affected enemies may make a Hard Acrobatics or Athletics check to break free.",
    cost: "1"
  },
  {
    name: "Goodberry",
    level: "1",
    actionSpeed: "Special Action",
    spellType: "Nature",
    range: "Touch",
    area: "Three berries",
    duration: "1 day",
    description: "Spend a minute to create three Goodberry fruits. Each fruit can be consumed to heal 1 HP and provides nutrition for a day. Consuming takes one minute (cannot be done in combat). Fruits last for one day.",
    cost: "1"
  },
  {
    name: "Gullibility",
    level: "1",
    actionSpeed: "Fast Action",
    spellType: "Bardic / Occult",
    range: "5 Units",
    area: "Single Target",
    duration: "10 minutes",
    description: "Magic check against Will of a target creature that you can see and that can see your face. If you succeed, all Speech and Performance checks against the target have advantage. They feel unexplained discomfort if cast with Occult magic.",
    cost: "1"
  },
  {
    name: "Healing Touch",
    level: "1",
    actionSpeed: "Fast Action",
    spellType: "Divine / Nature",
    range: "Touch",
    area: "Single Target",
    duration: "Instantaneous",
    description: "Heal a target for 2 HP, or 3 HP if cast with Divine magic. Outside of combat, heal the target to its maximum HP. If the target is dying, it becomes stabilized. Spend additional SP for +2 HP per point.",
    cost: "1+"
  },
  {
    name: "Hex",
    level: "1",
    actionSpeed: "Fast Action",
    spellType: "Occult",
    range: "10 Units",
    area: "Single Target",
    duration: "end of the next round",
    description: "Occult Magic check against target's Will. On success, each time the target receives damage from any Strike or Spell Attack, they also lose 1 life.",
    cost: "1"
  },
  {
    name: "Ice Knife",
    level: "1",
    actionSpeed: "Slow Action (Interruptible)",
    spellType: "Arcane",
    range: "10 Units",
    area: "Single Target + 2-unit splash",
    duration: "Instantaneous",
    description: "Magic check against Deflection. Launch an ice shard. On success:\n• Normal Success: Deal 3 ice damage.\n• Major Success: Deal 4 ice damage.\n• Critical Success: Deal 5 ice damage.\nThe shard shatters, sending shards to each enemy within 2 units. Use same roll: success deals 1 ice damage. Additional SP deals +1 damage to the target.",
    cost: "1+"
  },
  {
    name: "Leech",
    level: "1",
    actionSpeed: "Slow Action (Interruptible)",
    spellType: "Occult",
    range: "10 Units",
    area: "Single Target",
    duration: "Instantaneous",
    description: "Magic check against Deflection. On success:\n• Normal Success: Deal 2 Necrotic Damage and heal self/ally for 1 HP. Ignore 1 DR.\n• Major Success: Deal 3 Necrotic Damage and heal self/ally for 2 HP. Ignore 1 DR.\n• Critical Success: Deal 4 Necrotic Damage and heal self/ally for 3 HP. Ignore 1 DR.\nOn success, if you rolled 20, you or the ally healed gets +1 DR for 1 round. Additional SP deals +1 Necrotic damage.",
    cost: "1+"
  },
  {
    name: "Light",
    level: "Cantrip",
    actionSpeed: "Fast Action",
    spellType: "Arcane / Bardic / Divine / Nature",
    range: "15 Units",
    area: "Two balls or one item",
    duration: "Until dismissed/unconscious",
    description: "Create two stationary floating balls of light or make one item/limb luminous (6 units bright, 6 units dim). Enemy items/limbs require Magic check vs Deflection. Ends on unconsciousness, recast, or dismissal.",
    cost: "0"
  },
  {
    name: "Mage Hand",
    level: "Cantrip",
    actionSpeed: "Fast Action",
    spellType: "Arcane",
    range: "12 Units",
    area: "Spectral Hand",
    duration: "1 minute (estimated)",
    description: "[Mage Hand]",
    cost: "0"
  },
  {
    name: "Magic Missile",
    level: "1",
    actionSpeed: "Average Action",
    spellType: "Arcane",
    range: "15 units",
    area: "Up to 3 targets",
    duration: "Instantaneous",
    description: "Shoot three magical missiles. Each hits automatically and deals 1 force damage, ignoring all DR. Target same/multiple creatures. Additional SP shoots one more missile per point.",
    cost: "1+"
  },
  {
    name: "Magic Tricks",
    level: "Cantrip",
    actionSpeed: "Fast Action",
    spellType: "Arcane",
    range: "12 Units",
    area: "Small effects",
    duration: "Instantaneous",
    description: "[Like prestidigitation, but more free form.]",
    cost: "0"
  },
  {
    name: "Minor Illusion",
    level: "Cantrip",
    actionSpeed: "Fast Action",
    spellType: "Arcane / Bardic / Occult",
    range: "12 Units",
    area: "Created illusion",
    duration: "1 minute (estimated)",
    description: "[Minor Illusion]",
    cost: "0"
  },
  {
    name: "Message",
    level: "Cantrip",
    actionSpeed: "Fast Action",
    spellType: "Bardic",
    range: "50 Units",
    area: "Single Target",
    duration: "10 minutes",
    description: "Send a telepathic message to a target, and it may reply. Visible unless passing a Sneak or Sleight of Hand check.",
    cost: "0"
  },
  {
    name: "Mold Earth",
    level: "Cantrip",
    actionSpeed: "Fast Action",
    spellType: "Nature",
    range: "10 Units",
    area: "1 unit cube",
    duration: "Instantaneous (Permanent change)",
    description: "Manipulate ground. Choose one/both:\n• Create 1 unit cube of earth (Half/Full cover).\n• Dig 1 unit cube into the ground (Half cover).",
    cost: "0"
  },
  {
    name: "Natural Guidance",
    level: "Cantrip",
    actionSpeed: "Average Action",
    spellType: "Nature",
    range: "Touch",
    area: "Single Target",
    duration: "Until dismissed/unconscious",
    description: "Target gains advantage on Survival, Nature, Animal Handling, Cooking, Medicine, and Perception vs beasts/nature. Ends on unconsciousness, recast, or dismissal.",
    cost: "0"
  },
  {
    name: "Necrotic Bolt",
    level: "Cantrip",
    actionSpeed: "Average Action",
    spellType: "Occult",
    range: "10 Units",
    area: "Single Target",
    duration: "end of the next round",
    description: "Occult Magic check against Deflection. On success:\n• Normal Success: 1 Necrotic Damage (Ignore 1 DR), discouraged (-1 damage) 1 round.\n• Major Success: 1 Necrotic Damage (Ignore 1 DR), discouraged and vulnerable (-5 defenses) 1 round.\n• Critical Success: 2 Necrotic Damage (Ignore 1 DR), discouraged and vulnerable 1 round.\nNatural 20 also disorients target (-5 penalty).",
    cost: "0"
  },
  {
    name: "Radiant Beam",
    level: "Cantrip",
    actionSpeed: "Average Action",
    spellType: "Divine",
    range: "10 Units",
    area: "Single Target",
    duration: "end of the next round",
    description: "Divine Magic check against Deflection. On success:\n• Normal Success: 1 Radiant Damage (Ignore 1 DR).\n• Major Success: 1 Radiant Damage (Ignore 1 DR), discouraged (-1 damage) 1 round.\n• Critical Success: 2 Radiant Damage (Ignore 1 DR), discouraged 1 round.\nNatural 20 gives target disadvantage on attacks vs you/allies.",
    cost: "0"
  },
  {
    name: "Rainbow Eruption",
    level: "1",
    actionSpeed: "Slow Action (Interruptible)",
    spellType: "Nature / Bardic",
    range: "10 units",
    area: "5-unit radius",
    duration: "1 minute or end of combat",
    description: "Chaotic eruption. Magic check vs Deflection for enemies in radius. Successes become luminous: advantage on attacks against them, they give off light, and lose invisibility advantages.",
    cost: "1"
  },
  {
    name: "Sanctuary",
    level: "1",
    actionSpeed: "Slow Action (Interruptible)",
    spellType: "Divine",
    range: "15 units",
    area: "Single Target",
    duration: "end of the next two rounds",
    description: "Target cannot be targeted by any enemy. Ends if target performs any action other than Dash or Dodge.",
    cost: "1"
  },
  {
    name: "Scorching Rays",
    level: "1",
    actionSpeed: "Slow Action (Interruptible)",
    spellType: "Arcane",
    range: "10 Units",
    area: "Up to 3 rays",
    duration: "Instantaneous",
    description: "Pool of 4 fire damage. Distribute between one, two, or three rays. Magic vs Deflection. Success deals damage, failure deals half. Additional SP adds 2 fire damage per point.",
    cost: "1+"
  },
  {
    name: "Shield of Faith",
    level: "1",
    actionSpeed: "Slow Action (Interruptible)",
    spellType: "Divine",
    range: "15 units",
    area: "Single Target",
    duration: "end of the next two rounds",
    description: "Target gets +5 Deflection and +1 DR.",
    cost: "1"
  },
  {
    name: "Speak with Animals",
    level: "Cantrip",
    actionSpeed: "Fast Action",
    spellType: "Nature",
    range: "30 Units",
    area: "Single Target",
    duration: "10 minutes",
    description: "Animal understands you, and you understand them. Stops at end of duration or recast.",
    cost: "0"
  },
  {
    name: "Summon Beast",
    level: "1",
    actionSpeed: "Slow Action",
    spellType: "Nature",
    range: "10 Units",
    area: "Unoccupied space",
    duration: "1 day",
    description: "Requires 1 summon slot. Summons a Large or smaller beast. Separate actor you control. Command fast action required for specific actions.",
    cost: "1"
  },
  {
    name: "Summon Shade",
    level: "1",
    actionSpeed: "Slow Action (Interruptible)",
    spellType: "Occult",
    range: "10 Units",
    area: "Unoccupied space",
    duration: "1 minute",
    description: "Requires 1 summon slot. Summon spirit. Separate actor you control. Command fast action required for specific actions. Immediate Shadow Claw on summon.",
    cost: "1"
  },
  {
    name: "Thaumaturgy",
    level: "Cantrip",
    actionSpeed: "Fast Action",
    spellType: "Divine",
    range: "Self",
    area: "Self",
    duration: "Instantaneous",
    description: "You perform minor wonders.",
    cost: "0"
  },
  {
    name: "Vine Whip",
    level: "Cantrip",
    actionSpeed: "Fast Action",
    spellType: "Nature",
    range: "10 Units",
    area: "Single Target",
    duration: "Instantaneous",
    description: "Nature Magic vs Deflection. Thorny vine. On success:\n• Normal Success: 1 Piercing Damage (Ignore 1 DR), push/pull 1 unit.\n• Great Success: 1 Piercing Damage (Ignore 1 DR), push/pull 2 units.",
    cost: "0"
  }
];
